# Generated by Django 3.1.4 on 2020-12-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a ticker, like TSLA.', max_length=200)),
                ('recommendation', models.CharField(choices=[('NO', 'None'), ('ST', 'Stable Choice'), ('ME', 'Meme')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Your username', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OptionWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_days_active', models.DateTimeField(null=True)),
                ('collatoral', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='OptionPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('expiration_date', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_at_date', models.DecimalField(decimal_places=2, max_digits=12)),
                ('call_or_put', models.CharField(choices=[('C', 'Call'), ('P', 'P')], default='P', max_length=1)),
                ('option_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.optionwheel')),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stockticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
    ]
