# Generated by Django 3.1.4 on 2020-12-31 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a ticker, like TSLA.', max_length=200, unique=True)),
                ('recommendation', models.CharField(choices=[('NO', 'None'), ('ST', 'Stable Choice'), ('HV', 'High Volatility')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OptionWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField()),
                ('total_profit', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('total_days_active', models.IntegerField(default=None, null=True)),
                ('collatoral', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stockticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('expiration_date', models.DateField()),
                ('strike', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_at_date', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('call_or_put', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], default='P', max_length=1)),
                ('option_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.optionwheel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
