# Generated by Django 3.1.4 on 2020-12-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201219_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionwheel',
            name='collatoral',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='optionwheel',
            name='total_days_active',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optionwheel',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
