# Generated by Django 3.1.4 on 2022-10-24 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_auto_20210117_1541"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="optionpurchase",
            options={"ordering": ["-expiration_date", "-purchase_date"]},
        ),
        migrations.AlterField(
            model_name="optionpurchase",
            name="option_wheel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_purchases",
                to="catalog.optionwheel",
            ),
        ),
    ]
