# Generated by Django 3.1.4 on 2020-12-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201224_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionpurchase',
            name='call_or_put',
            field=models.CharField(choices=[('C', 'Call'), ('P', 'Put')], default='P', max_length=1),
        ),
    ]
