# Generated by Django 3.1.4 on 2020-12-31 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201228_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionpurchase',
            name='stock_ticker',
        ),
        migrations.AddField(
            model_name='optionwheel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='optionwheel',
            name='stock_ticker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.stockticker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='name',
            field=models.CharField(help_text='Enter a ticker, like TSLA.', max_length=200, unique=True),
        ),
    ]
